### ISSUE TITLE
Does not always edit the targeted sign

### ISSUE THREAD

**Issue by SiuanSong** [Deltik/SignEdit#20]
Editing a sign does not always edit the sign you are trying to target. It seems to target the sign at your characters eye level instead of the sign targeted by your mouse.

Stand in front of a wall of signs and try to edit one thats not directly in your eye level view by placing your cursor over it.

I had this same issue with EssentialsX /editsign command, this is what they did to fix it.

https://github.com/EssentialsX/Essentials/pull/3763

**Comment by Deltik** [comment]
@SiuanSong: Thanks for reporting the bug!

This has now been fixed in [SignEdit for Bukkit v1.12.5](https://github.com/Deltik/SignEdit/releases/tag/v1.12.5), which you can directly download [here](https://github.com/Deltik/SignEdit/releases/download/v1.12.5/SignEdit-1.12.5.jar).

**Comment by Deltik** [comment]
@SiuanSong: Thanks for reporting the bug!

This has now been fixed in [SignEdit for Bukkit v1.12.6](https://github.com/Deltik/SignEdit/releases/tag/v1.12.6), which you can directly download [here](https://github.com/Deltik/SignEdit/releases/download/v1.12.6/SignEdit-1.12.6.jar).
