### ISSUE TITLE
Players can edit signs on plots they do not have build access for

### ISSUE THREAD

**Issue by SecretlyJealous** [Deltik/SignEdit#31]
Hello, I'm using this plugin with PlotSquared however any player can edit a sign regardless of whether they have permission to build in the plot. Is it possible for this to be fixed?

**Comment by Deltik** [comment]
@SecretlyJealous: A quick search in the https://github.com/IntellectualSites/PlotSquared repository revealed that the plugin does not check the [`SignChangeEvent`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/SignChangeEvent.html) of the sign text being set.

In `./SignEdit/config.yml` under `compatibility`, can you try changing the value of `edit-validation` from `Standard` to `Extra`?  This will cause SignEdit for Bukkit to emit [`BlockBreakEvent`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockBreakEvent.html) and [`BlockPlaceEvent`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockPlaceEvent.html), which [the other plugin does handle](https://github.com/IntellectualSites/PlotSquared/blob/b5bc1988e59ad5fcd53334c9243f5218363b38bd/Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java#L335).

**Comment by SecretlyJealous** [comment]
@Deltik Thanks! Changing the edit-validation from standard to extra worked.
