### ISSUE TITLE
SignEdit preventing the creation of Glowing Signs and Dyed text

### ISSUE THREAD

**Issue by baailey** [Deltik/SignEdit#41]
Currently unable to create a glowing sign or being unable to dye the colour of the text on the sign. Causes the user to open the sign edit menu when clicking on the sign. This functions fine in Vanilla.

Server version: git-Paper-83 (MC: 1.20.1)
Plugin version: 1.14.0

**Comment by Deltik** [comment]
@baailey: Thanks for reporting this bug!

It has now been fixed in [SignEdit for Bukkit v1.14.1](https://github.com/Deltik/SignEdit/releases/tag/v1.14.1), which you can directly download [here](https://github.com/Deltik/SignEdit/releases/download/v1.14.1/SignEdit-1.14.1.jar).
