### ISSUE TITLE
Copy / Paste can be used to copy ChestShop signs

### ISSUE THREAD

**Issue by baailey** [Deltik/SignEdit#43]
SignEdit currently allows copying and pasting [ChestShop](https://www.spigotmc.org/resources/chestshop.51856/) signs, allowing users who don't own the shop to make their own Chest Shops under other players names.

When you try make a ChestShop through the standard method, the shop plugin will reject the creation as players should only be able to make their own shop, however SignEdit can be used to bypass this block

**Comment by Deltik** [comment]
Hello @baailey,

I can't reproduce the issue as described:

![SignEdit#43-1](https://github.com/user-attachments/assets/dac42428-7866-4272-b064-fd2d0dd02331)

It also does not seem to be possible to modify an existing ChestShop sign to change the user to another one:

![SignEdit#43-2](https://github.com/user-attachments/assets/bea00df3-36ab-449d-9725-064f626bbd3c)

These screenshots were from a server using the default `compatibility.edit-validation: "Standard"` setting, which emits `SignChangeEvent` to other plugins.

SignEdit for Bukkit does not have a per-user override to force sign changes onto other plugins, so please make sure you did not grant excessive permissions in other plugins to bypass ChestShop's restrictions.

If you can provide more detailed steps and configurations to reproduce the issue, I'll reopen the issue and reevaluate the evidence, but from what I can tell, SignEdit for Bukkit is correctly being denied permission to edit a ChestShop sign.

**Comment by baailey** [comment]
my edit validation is set to extra

here is a vid of exactly what I've done: https://imgur.com/a/0ZUdQ1H

**Comment by Deltik** [comment]
@baailey, that looks like intended behavior if you were player `baailey`.  It seems that ChestShop allows the same user to create duplicate signs over other chests.  I'm able to do this on my test server when the first line is `Deltik` (my username).

**Comment by baailey** [comment]
no that was done on a different account

**Comment by Deltik** [comment]
Does that player have the `ChestShop.admin` permission?  If that permission is set, they can override the sign contents freely.

**Comment by baailey** [comment]
it does not

**Comment by Deltik** [comment]
Okay, I see that I was not able to write the text of a new sign for another player but was able to copy a ChestShop sign from another player onto a blank sign:

![SignEdit#43-3](https://github.com/user-attachments/assets/321cb90e-9c86-4c86-acaa-a9c16197ce40)

I am now checking to see if this is a bug in SignEdit for Bukkit.

**Comment by Deltik** [comment]
This is now a confirmed bug with SignEdit for Bukkit affecting `compatibility.edit-validation: "Extra"`.

**Comment by Deltik** [comment]
@baailey: Thanks for reporting this bug!

It has now been fixed in [SignEdit for Bukkit v1.14.5](https://github.com/Deltik/SignEdit/releases/tag/v1.14.5), which you can directly download [here](https://github.com/Deltik/SignEdit/releases/download/v1.14.5/SignEdit-1.14.5.jar).

**Comment by baailey** [comment]
wonderful, thanks
