### ISSUE TITLE
Sign Ui on Spigot and Paperspigot 1.8.8

### ISSUE THREAD

**Issue by Tigerpanzer02** [Deltik/SignEdit#6]
When I do the /sign ui command and click on one sign it says this error

Log
> 
> [19:49:17] [Server thread/INFO]: Tigerpanzer_02 issued server command: /sign ui
> [19:49:29] [Server thread/ERROR]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.BlockPosition$PooledBlockPosition
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:264)
> 	at org.deltik.mc.signedit.MinecraftReflector.getMinecraftServerClass(MinecraftReflector.java:18)
> 	at org.deltik.mc.signedit.committers.UiSignEditCommit.commit(UiSignEditCommit.java:52)
> 	at org.deltik.mc.signedit.committers.SignEditCommit.validatedCommit(SignEditCommit.java:24)
> 	at org.deltik.mc.signedit.listeners.Interact.onInteract(Interact.java:30)
> 	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
> 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228)
> 	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463)
> 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763)
> 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
> 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
> 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
> 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
> 	at java.lang.Thread.run(Thread.java:748)
>

**Comment by Deltik** [comment]
@Tigerpanzer02: Thanks for reporting the bug!

This has now been fixed in [SignEdit for Bukkit v1.9.2](https://github.com/Deltik/SignEdit/releases/tag/v1.9.2), which you can directly download [here](https://github.com/Deltik/SignEdit/releases/download/v1.9.2/SignEdit-1.9.2.jar).

**Comment by Deltik** [comment]
@Tigerpanzer02: While fixing this bug, I discovered another one.  This bug causes the last edit with `/sign ui` to be rolled back after the player disconnects.  I'll be working on a fix, but this fix is going to take longer.

The workaround for now is to run `/se ui` on any sign before logging out.
